//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrello {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carrello.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DELETE FROM Tabella1 WHERE Id=2.
        /// </summary>
        internal static string CancellaDati {
            get {
                return ResourceManager.GetString("CancellaDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert into Ordini(IdSessione, Totale) values (@IdSessione, @Totale).
        /// </summary>
        internal static string CreaOrdine {
            get {
                return ResourceManager.GetString("CreaOrdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert into Sessione (DataOra, IndirizzoIp) values (@DataOra,@IndirizzoIp).
        /// </summary>
        internal static string CreaSessione {
            get {
                return ResourceManager.GetString("CreaSessione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select * From Articoli A
        ///Inner Join Carrello C on A.Id=C.IdArticolo where IdSessione=@IdSessione.
        /// </summary>
        internal static string GetCarrello {
            get {
                return ResourceManager.GetString("GetCarrello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select * from Sessione where IndirizzoIp = @IndirizzoIp.
        /// </summary>
        internal static string GetSessione {
            get {
                return ResourceManager.GetString("GetSessione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select COUNT(Id) From Sessione Where IndirizzoIp =@IndirizzoIp.
        /// </summary>
        internal static string HaSessione {
            get {
                return ResourceManager.GetString("HaSessione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert into Carrello (IdSessione,IdArticolo) Values (@IdSessione, @IdArticolo).
        /// </summary>
        internal static string InserisciArticolo {
            get {
                return ResourceManager.GetString("InserisciArticolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select * From Articoli.
        /// </summary>
        internal static string LeggiArticoli {
            get {
                return ResourceManager.GetString("LeggiArticoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SELECT * FROM Tabella1.
        /// </summary>
        internal static string LeggiDati {
            get {
                return ResourceManager.GetString("LeggiDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete from Ordini where IdSessione=@IdSessione.
        /// </summary>
        internal static string RimuoviOrdini {
            get {
                return ResourceManager.GetString("RimuoviOrdini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO Tabella1(Id, Descrizione) VALUES (@Id, @Descrizione).
        /// </summary>
        internal static string ScriviDati {
            get {
                return ResourceManager.GetString("ScriviDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DELETE from Carrello where IdSessione=@IdSessione.
        /// </summary>
        internal static string SvuotaCarrello {
            get {
                return ResourceManager.GetString("SvuotaCarrello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UPDATE Tabella1 SET Id = 5, Descrizione= &apos;Test 5&apos; WHERE Id = 4;.
        /// </summary>
        internal static string UpdateDati {
            get {
                return ResourceManager.GetString("UpdateDati", resourceCulture);
            }
        }
    }
}
